### ISSUE TITLE
Bertanya tentang shopee endpoint api

### ISSUE THREAD

**Issue by codevjs** [structuredman/flasher2-src#3]
apakah bisa langsung hit endpoint https://mall.shopee.co.id/api/v2/checkout/place_order untuk mengefisienkan waktu request ketika flash sale?

apakah item harus di tambahkan ke cart atau bisa langsung place_order?

**Comment by structuredman** [comment]
dulu pas ane coba gabisa kalo langsung place_order, jadi harus add_to_cart dulu.

**Comment by codevjs** [comment]
saya dapat shortcut 
1. get info item https://mall.shopee.co.id/api/v4/item/get?itemid=${this.itemId}&shopid=${this.shopId}
2. kemudian get checkout https://mall.shopee.co.id/api/v2/checkout/get
3. terkahir place order https://shopee.co.id/api/v2/checkout/place_order

langkah ini work, sudah saya coba jadi ngga perlu buang waktu untuk tambahkan item ke cart
